# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Contact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'user_key': 'int',
        'name': 'str',
        'number': 'str',
        'channel': 'str',
        'blocked': 'int',
        'created': 'datetime',
        'modified': 'datetime',
        'user': 'User',
        'group_contacts': 'list[GroupContact]'
    }

    attribute_map = {
        'key': 'key',
        'user_key': 'userKey',
        'name': 'name',
        'number': 'number',
        'channel': 'channel',
        'blocked': 'blocked',
        'created': 'created',
        'modified': 'modified',
        'user': 'user',
        'group_contacts': 'groupContacts'
    }

    def __init__(self, key=None, user_key=None, name=None, number=None, channel=None, blocked=None, created=None, modified=None, user=None, group_contacts=None):  # noqa: E501
        """Contact - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._user_key = None
        self._name = None
        self._number = None
        self._channel = None
        self._blocked = None
        self._created = None
        self._modified = None
        self._user = None
        self._group_contacts = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if user_key is not None:
            self.user_key = user_key
        if name is not None:
            self.name = name
        if number is not None:
            self.number = number
        if channel is not None:
            self.channel = channel
        if blocked is not None:
            self.blocked = blocked
        if created is not None:
            self.created = created
        if modified is not None:
            self.modified = modified
        if user is not None:
            self.user = user
        if group_contacts is not None:
            self.group_contacts = group_contacts

    @property
    def key(self):
        """Gets the key of this Contact.  # noqa: E501


        :return: The key of this Contact.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this Contact.


        :param key: The key of this Contact.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def user_key(self):
        """Gets the user_key of this Contact.  # noqa: E501


        :return: The user_key of this Contact.  # noqa: E501
        :rtype: int
        """
        return self._user_key

    @user_key.setter
    def user_key(self, user_key):
        """Sets the user_key of this Contact.


        :param user_key: The user_key of this Contact.  # noqa: E501
        :type: int
        """

        self._user_key = user_key

    @property
    def name(self):
        """Gets the name of this Contact.  # noqa: E501


        :return: The name of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Contact.


        :param name: The name of this Contact.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def number(self):
        """Gets the number of this Contact.  # noqa: E501


        :return: The number of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this Contact.


        :param number: The number of this Contact.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def channel(self):
        """Gets the channel of this Contact.  # noqa: E501


        :return: The channel of this Contact.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this Contact.


        :param channel: The channel of this Contact.  # noqa: E501
        :type: str
        """

        self._channel = channel

    @property
    def blocked(self):
        """Gets the blocked of this Contact.  # noqa: E501


        :return: The blocked of this Contact.  # noqa: E501
        :rtype: int
        """
        return self._blocked

    @blocked.setter
    def blocked(self, blocked):
        """Sets the blocked of this Contact.


        :param blocked: The blocked of this Contact.  # noqa: E501
        :type: int
        """

        self._blocked = blocked

    @property
    def created(self):
        """Gets the created of this Contact.  # noqa: E501


        :return: The created of this Contact.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Contact.


        :param created: The created of this Contact.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def modified(self):
        """Gets the modified of this Contact.  # noqa: E501


        :return: The modified of this Contact.  # noqa: E501
        :rtype: datetime
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this Contact.


        :param modified: The modified of this Contact.  # noqa: E501
        :type: datetime
        """

        self._modified = modified

    @property
    def user(self):
        """Gets the user of this Contact.  # noqa: E501


        :return: The user of this Contact.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Contact.


        :param user: The user of this Contact.  # noqa: E501
        :type: User
        """

        self._user = user

    @property
    def group_contacts(self):
        """Gets the group_contacts of this Contact.  # noqa: E501


        :return: The group_contacts of this Contact.  # noqa: E501
        :rtype: list[GroupContact]
        """
        return self._group_contacts

    @group_contacts.setter
    def group_contacts(self, group_contacts):
        """Sets the group_contacts of this Contact.


        :param group_contacts: The group_contacts of this Contact.  # noqa: E501
        :type: list[GroupContact]
        """

        self._group_contacts = group_contacts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Contact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Contact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
