# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExtendedChannelContent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'site_key': 'int',
        'position': 'int',
        'list_type': 'HeadlineListType',
        'expire': 'datetime',
        'site': 'Site',
        'channel_content': 'ChannelContent'
    }

    attribute_map = {
        'key': 'key',
        'site_key': 'siteKey',
        'position': 'position',
        'list_type': 'listType',
        'expire': 'expire',
        'site': 'site',
        'channel_content': 'channelContent'
    }

    def __init__(self, key=None, site_key=None, position=None, list_type=None, expire=None, site=None, channel_content=None):  # noqa: E501
        """ExtendedChannelContent - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._site_key = None
        self._position = None
        self._list_type = None
        self._expire = None
        self._site = None
        self._channel_content = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if site_key is not None:
            self.site_key = site_key
        if position is not None:
            self.position = position
        if list_type is not None:
            self.list_type = list_type
        if expire is not None:
            self.expire = expire
        if site is not None:
            self.site = site
        if channel_content is not None:
            self.channel_content = channel_content

    @property
    def key(self):
        """Gets the key of this ExtendedChannelContent.  # noqa: E501


        :return: The key of this ExtendedChannelContent.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this ExtendedChannelContent.


        :param key: The key of this ExtendedChannelContent.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def site_key(self):
        """Gets the site_key of this ExtendedChannelContent.  # noqa: E501


        :return: The site_key of this ExtendedChannelContent.  # noqa: E501
        :rtype: int
        """
        return self._site_key

    @site_key.setter
    def site_key(self, site_key):
        """Sets the site_key of this ExtendedChannelContent.


        :param site_key: The site_key of this ExtendedChannelContent.  # noqa: E501
        :type: int
        """

        self._site_key = site_key

    @property
    def position(self):
        """Gets the position of this ExtendedChannelContent.  # noqa: E501


        :return: The position of this ExtendedChannelContent.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this ExtendedChannelContent.


        :param position: The position of this ExtendedChannelContent.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def list_type(self):
        """Gets the list_type of this ExtendedChannelContent.  # noqa: E501


        :return: The list_type of this ExtendedChannelContent.  # noqa: E501
        :rtype: HeadlineListType
        """
        return self._list_type

    @list_type.setter
    def list_type(self, list_type):
        """Sets the list_type of this ExtendedChannelContent.


        :param list_type: The list_type of this ExtendedChannelContent.  # noqa: E501
        :type: HeadlineListType
        """

        self._list_type = list_type

    @property
    def expire(self):
        """Gets the expire of this ExtendedChannelContent.  # noqa: E501


        :return: The expire of this ExtendedChannelContent.  # noqa: E501
        :rtype: datetime
        """
        return self._expire

    @expire.setter
    def expire(self, expire):
        """Sets the expire of this ExtendedChannelContent.


        :param expire: The expire of this ExtendedChannelContent.  # noqa: E501
        :type: datetime
        """

        self._expire = expire

    @property
    def site(self):
        """Gets the site of this ExtendedChannelContent.  # noqa: E501


        :return: The site of this ExtendedChannelContent.  # noqa: E501
        :rtype: Site
        """
        return self._site

    @site.setter
    def site(self, site):
        """Sets the site of this ExtendedChannelContent.


        :param site: The site of this ExtendedChannelContent.  # noqa: E501
        :type: Site
        """

        self._site = site

    @property
    def channel_content(self):
        """Gets the channel_content of this ExtendedChannelContent.  # noqa: E501


        :return: The channel_content of this ExtendedChannelContent.  # noqa: E501
        :rtype: ChannelContent
        """
        return self._channel_content

    @channel_content.setter
    def channel_content(self, channel_content):
        """Sets the channel_content of this ExtendedChannelContent.


        :param channel_content: The channel_content of this ExtendedChannelContent.  # noqa: E501
        :type: ChannelContent
        """

        self._channel_content = channel_content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExtendedChannelContent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExtendedChannelContent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
