# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ItunesCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'name': 'str',
        'display_name': 'str',
        'podcast_itunes_categorys': 'list[PodcastItunesCategory]'
    }

    attribute_map = {
        'key': 'key',
        'name': 'name',
        'display_name': 'displayName',
        'podcast_itunes_categorys': 'podcastItunesCategorys'
    }

    def __init__(self, key=None, name=None, display_name=None, podcast_itunes_categorys=None):  # noqa: E501
        """ItunesCategory - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._name = None
        self._display_name = None
        self._podcast_itunes_categorys = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if name is not None:
            self.name = name
        if display_name is not None:
            self.display_name = display_name
        if podcast_itunes_categorys is not None:
            self.podcast_itunes_categorys = podcast_itunes_categorys

    @property
    def key(self):
        """Gets the key of this ItunesCategory.  # noqa: E501


        :return: The key of this ItunesCategory.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this ItunesCategory.


        :param key: The key of this ItunesCategory.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def name(self):
        """Gets the name of this ItunesCategory.  # noqa: E501


        :return: The name of this ItunesCategory.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ItunesCategory.


        :param name: The name of this ItunesCategory.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def display_name(self):
        """Gets the display_name of this ItunesCategory.  # noqa: E501


        :return: The display_name of this ItunesCategory.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ItunesCategory.


        :param display_name: The display_name of this ItunesCategory.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def podcast_itunes_categorys(self):
        """Gets the podcast_itunes_categorys of this ItunesCategory.  # noqa: E501


        :return: The podcast_itunes_categorys of this ItunesCategory.  # noqa: E501
        :rtype: list[PodcastItunesCategory]
        """
        return self._podcast_itunes_categorys

    @podcast_itunes_categorys.setter
    def podcast_itunes_categorys(self, podcast_itunes_categorys):
        """Sets the podcast_itunes_categorys of this ItunesCategory.


        :param podcast_itunes_categorys: The podcast_itunes_categorys of this ItunesCategory.  # noqa: E501
        :type: list[PodcastItunesCategory]
        """

        self._podcast_itunes_categorys = podcast_itunes_categorys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItunesCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItunesCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
