# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Platoon(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'sport_key': 'int',
        'name': 'str',
        'abbreviation': 'str',
        'position_groups': 'list[PositionGroup]',
        'sport': 'Sport'
    }

    attribute_map = {
        'key': 'key',
        'sport_key': 'sportKey',
        'name': 'name',
        'abbreviation': 'abbreviation',
        'position_groups': 'positionGroups',
        'sport': 'sport'
    }

    def __init__(self, key=None, sport_key=None, name=None, abbreviation=None, position_groups=None, sport=None):  # noqa: E501
        """Platoon - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._sport_key = None
        self._name = None
        self._abbreviation = None
        self._position_groups = None
        self._sport = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if sport_key is not None:
            self.sport_key = sport_key
        if name is not None:
            self.name = name
        if abbreviation is not None:
            self.abbreviation = abbreviation
        if position_groups is not None:
            self.position_groups = position_groups
        if sport is not None:
            self.sport = sport

    @property
    def key(self):
        """Gets the key of this Platoon.  # noqa: E501


        :return: The key of this Platoon.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this Platoon.


        :param key: The key of this Platoon.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def sport_key(self):
        """Gets the sport_key of this Platoon.  # noqa: E501


        :return: The sport_key of this Platoon.  # noqa: E501
        :rtype: int
        """
        return self._sport_key

    @sport_key.setter
    def sport_key(self, sport_key):
        """Sets the sport_key of this Platoon.


        :param sport_key: The sport_key of this Platoon.  # noqa: E501
        :type: int
        """

        self._sport_key = sport_key

    @property
    def name(self):
        """Gets the name of this Platoon.  # noqa: E501


        :return: The name of this Platoon.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Platoon.


        :param name: The name of this Platoon.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def abbreviation(self):
        """Gets the abbreviation of this Platoon.  # noqa: E501


        :return: The abbreviation of this Platoon.  # noqa: E501
        :rtype: str
        """
        return self._abbreviation

    @abbreviation.setter
    def abbreviation(self, abbreviation):
        """Sets the abbreviation of this Platoon.


        :param abbreviation: The abbreviation of this Platoon.  # noqa: E501
        :type: str
        """

        self._abbreviation = abbreviation

    @property
    def position_groups(self):
        """Gets the position_groups of this Platoon.  # noqa: E501


        :return: The position_groups of this Platoon.  # noqa: E501
        :rtype: list[PositionGroup]
        """
        return self._position_groups

    @position_groups.setter
    def position_groups(self, position_groups):
        """Sets the position_groups of this Platoon.


        :param position_groups: The position_groups of this Platoon.  # noqa: E501
        :type: list[PositionGroup]
        """

        self._position_groups = position_groups

    @property
    def sport(self):
        """Gets the sport of this Platoon.  # noqa: E501


        :return: The sport of this Platoon.  # noqa: E501
        :rtype: Sport
        """
        return self._sport

    @sport.setter
    def sport(self, sport):
        """Sets the sport of this Platoon.


        :param sport: The sport of this Platoon.  # noqa: E501
        :type: Sport
        """

        self._sport = sport

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Platoon, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Platoon):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
