# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PositionGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'platoon_key': 'int',
        'name': 'str',
        'abbreviation': 'str',
        'platoon': 'Platoon',
        'positions': 'list[Position]'
    }

    attribute_map = {
        'key': 'key',
        'platoon_key': 'platoonKey',
        'name': 'name',
        'abbreviation': 'abbreviation',
        'platoon': 'platoon',
        'positions': 'positions'
    }

    def __init__(self, key=None, platoon_key=None, name=None, abbreviation=None, platoon=None, positions=None):  # noqa: E501
        """PositionGroup - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._platoon_key = None
        self._name = None
        self._abbreviation = None
        self._platoon = None
        self._positions = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if platoon_key is not None:
            self.platoon_key = platoon_key
        if name is not None:
            self.name = name
        if abbreviation is not None:
            self.abbreviation = abbreviation
        if platoon is not None:
            self.platoon = platoon
        if positions is not None:
            self.positions = positions

    @property
    def key(self):
        """Gets the key of this PositionGroup.  # noqa: E501


        :return: The key of this PositionGroup.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this PositionGroup.


        :param key: The key of this PositionGroup.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def platoon_key(self):
        """Gets the platoon_key of this PositionGroup.  # noqa: E501


        :return: The platoon_key of this PositionGroup.  # noqa: E501
        :rtype: int
        """
        return self._platoon_key

    @platoon_key.setter
    def platoon_key(self, platoon_key):
        """Sets the platoon_key of this PositionGroup.


        :param platoon_key: The platoon_key of this PositionGroup.  # noqa: E501
        :type: int
        """

        self._platoon_key = platoon_key

    @property
    def name(self):
        """Gets the name of this PositionGroup.  # noqa: E501


        :return: The name of this PositionGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PositionGroup.


        :param name: The name of this PositionGroup.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def abbreviation(self):
        """Gets the abbreviation of this PositionGroup.  # noqa: E501


        :return: The abbreviation of this PositionGroup.  # noqa: E501
        :rtype: str
        """
        return self._abbreviation

    @abbreviation.setter
    def abbreviation(self, abbreviation):
        """Sets the abbreviation of this PositionGroup.


        :param abbreviation: The abbreviation of this PositionGroup.  # noqa: E501
        :type: str
        """

        self._abbreviation = abbreviation

    @property
    def platoon(self):
        """Gets the platoon of this PositionGroup.  # noqa: E501


        :return: The platoon of this PositionGroup.  # noqa: E501
        :rtype: Platoon
        """
        return self._platoon

    @platoon.setter
    def platoon(self, platoon):
        """Sets the platoon of this PositionGroup.


        :param platoon: The platoon of this PositionGroup.  # noqa: E501
        :type: Platoon
        """

        self._platoon = platoon

    @property
    def positions(self):
        """Gets the positions of this PositionGroup.  # noqa: E501


        :return: The positions of this PositionGroup.  # noqa: E501
        :rtype: list[Position]
        """
        return self._positions

    @positions.setter
    def positions(self, positions):
        """Sets the positions of this PositionGroup.


        :param positions: The positions of this PositionGroup.  # noqa: E501
        :type: list[Position]
        """

        self._positions = positions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PositionGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PositionGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
