# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PostAsset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'post_key': 'int',
        'asset_key': 'int',
        'order': 'int',
        'post': 'Post',
        'asset': 'Asset'
    }

    attribute_map = {
        'key': 'key',
        'post_key': 'postKey',
        'asset_key': 'assetKey',
        'order': 'order',
        'post': 'post',
        'asset': 'asset'
    }

    def __init__(self, key=None, post_key=None, asset_key=None, order=None, post=None, asset=None):  # noqa: E501
        """PostAsset - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._post_key = None
        self._asset_key = None
        self._order = None
        self._post = None
        self._asset = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if post_key is not None:
            self.post_key = post_key
        if asset_key is not None:
            self.asset_key = asset_key
        if order is not None:
            self.order = order
        if post is not None:
            self.post = post
        if asset is not None:
            self.asset = asset

    @property
    def key(self):
        """Gets the key of this PostAsset.  # noqa: E501


        :return: The key of this PostAsset.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this PostAsset.


        :param key: The key of this PostAsset.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def post_key(self):
        """Gets the post_key of this PostAsset.  # noqa: E501


        :return: The post_key of this PostAsset.  # noqa: E501
        :rtype: int
        """
        return self._post_key

    @post_key.setter
    def post_key(self, post_key):
        """Sets the post_key of this PostAsset.


        :param post_key: The post_key of this PostAsset.  # noqa: E501
        :type: int
        """

        self._post_key = post_key

    @property
    def asset_key(self):
        """Gets the asset_key of this PostAsset.  # noqa: E501


        :return: The asset_key of this PostAsset.  # noqa: E501
        :rtype: int
        """
        return self._asset_key

    @asset_key.setter
    def asset_key(self, asset_key):
        """Sets the asset_key of this PostAsset.


        :param asset_key: The asset_key of this PostAsset.  # noqa: E501
        :type: int
        """

        self._asset_key = asset_key

    @property
    def order(self):
        """Gets the order of this PostAsset.  # noqa: E501


        :return: The order of this PostAsset.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this PostAsset.


        :param order: The order of this PostAsset.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def post(self):
        """Gets the post of this PostAsset.  # noqa: E501


        :return: The post of this PostAsset.  # noqa: E501
        :rtype: Post
        """
        return self._post

    @post.setter
    def post(self, post):
        """Sets the post of this PostAsset.


        :param post: The post of this PostAsset.  # noqa: E501
        :type: Post
        """

        self._post = post

    @property
    def asset(self):
        """Gets the asset of this PostAsset.  # noqa: E501


        :return: The asset of this PostAsset.  # noqa: E501
        :rtype: Asset
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this PostAsset.


        :param asset: The asset of this PostAsset.  # noqa: E501
        :type: Asset
        """

        self._asset = asset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostAsset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostAsset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
