# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SiteUrl(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'base_url': 'str',
        'site_key': 'int',
        'site': 'Site',
        'primary': 'PrimaryType',
        'is_primary': 'bool',
        'is_subdomain_only': 'bool',
        'is_segment_based': 'bool'
    }

    attribute_map = {
        'key': 'key',
        'base_url': 'baseUrl',
        'site_key': 'siteKey',
        'site': 'site',
        'primary': 'primary',
        'is_primary': 'isPrimary',
        'is_subdomain_only': 'isSubdomainOnly',
        'is_segment_based': 'isSegmentBased'
    }

    def __init__(self, key=None, base_url=None, site_key=None, site=None, primary=None, is_primary=None, is_subdomain_only=None, is_segment_based=None):  # noqa: E501
        """SiteUrl - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._base_url = None
        self._site_key = None
        self._site = None
        self._primary = None
        self._is_primary = None
        self._is_subdomain_only = None
        self._is_segment_based = None
        self.discriminator = None
        if key is not None:
            self.key = key
        self.base_url = base_url
        self.site_key = site_key
        if site is not None:
            self.site = site
        if primary is not None:
            self.primary = primary
        if is_primary is not None:
            self.is_primary = is_primary
        if is_subdomain_only is not None:
            self.is_subdomain_only = is_subdomain_only
        if is_segment_based is not None:
            self.is_segment_based = is_segment_based

    @property
    def key(self):
        """Gets the key of this SiteUrl.  # noqa: E501


        :return: The key of this SiteUrl.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this SiteUrl.


        :param key: The key of this SiteUrl.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def base_url(self):
        """Gets the base_url of this SiteUrl.  # noqa: E501


        :return: The base_url of this SiteUrl.  # noqa: E501
        :rtype: str
        """
        return self._base_url

    @base_url.setter
    def base_url(self, base_url):
        """Sets the base_url of this SiteUrl.


        :param base_url: The base_url of this SiteUrl.  # noqa: E501
        :type: str
        """
        if base_url is None:
            raise ValueError("Invalid value for `base_url`, must not be `None`")  # noqa: E501

        self._base_url = base_url

    @property
    def site_key(self):
        """Gets the site_key of this SiteUrl.  # noqa: E501


        :return: The site_key of this SiteUrl.  # noqa: E501
        :rtype: int
        """
        return self._site_key

    @site_key.setter
    def site_key(self, site_key):
        """Sets the site_key of this SiteUrl.


        :param site_key: The site_key of this SiteUrl.  # noqa: E501
        :type: int
        """
        if site_key is None:
            raise ValueError("Invalid value for `site_key`, must not be `None`")  # noqa: E501

        self._site_key = site_key

    @property
    def site(self):
        """Gets the site of this SiteUrl.  # noqa: E501


        :return: The site of this SiteUrl.  # noqa: E501
        :rtype: Site
        """
        return self._site

    @site.setter
    def site(self, site):
        """Sets the site of this SiteUrl.


        :param site: The site of this SiteUrl.  # noqa: E501
        :type: Site
        """

        self._site = site

    @property
    def primary(self):
        """Gets the primary of this SiteUrl.  # noqa: E501


        :return: The primary of this SiteUrl.  # noqa: E501
        :rtype: PrimaryType
        """
        return self._primary

    @primary.setter
    def primary(self, primary):
        """Sets the primary of this SiteUrl.


        :param primary: The primary of this SiteUrl.  # noqa: E501
        :type: PrimaryType
        """

        self._primary = primary

    @property
    def is_primary(self):
        """Gets the is_primary of this SiteUrl.  # noqa: E501


        :return: The is_primary of this SiteUrl.  # noqa: E501
        :rtype: bool
        """
        return self._is_primary

    @is_primary.setter
    def is_primary(self, is_primary):
        """Sets the is_primary of this SiteUrl.


        :param is_primary: The is_primary of this SiteUrl.  # noqa: E501
        :type: bool
        """

        self._is_primary = is_primary

    @property
    def is_subdomain_only(self):
        """Gets the is_subdomain_only of this SiteUrl.  # noqa: E501


        :return: The is_subdomain_only of this SiteUrl.  # noqa: E501
        :rtype: bool
        """
        return self._is_subdomain_only

    @is_subdomain_only.setter
    def is_subdomain_only(self, is_subdomain_only):
        """Sets the is_subdomain_only of this SiteUrl.


        :param is_subdomain_only: The is_subdomain_only of this SiteUrl.  # noqa: E501
        :type: bool
        """

        self._is_subdomain_only = is_subdomain_only

    @property
    def is_segment_based(self):
        """Gets the is_segment_based of this SiteUrl.  # noqa: E501


        :return: The is_segment_based of this SiteUrl.  # noqa: E501
        :rtype: bool
        """
        return self._is_segment_based

    @is_segment_based.setter
    def is_segment_based(self, is_segment_based):
        """Sets the is_segment_based of this SiteUrl.


        :param is_segment_based: The is_segment_based of this SiteUrl.  # noqa: E501
        :type: bool
        """

        self._is_segment_based = is_segment_based

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SiteUrl, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SiteUrl):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
