# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubscriptionSite(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'subscription_key': 'int',
        'site_key': 'int',
        'subscription': 'Subscription',
        'site': 'Site'
    }

    attribute_map = {
        'key': 'key',
        'subscription_key': 'subscriptionKey',
        'site_key': 'siteKey',
        'subscription': 'subscription',
        'site': 'site'
    }

    def __init__(self, key=None, subscription_key=None, site_key=None, subscription=None, site=None):  # noqa: E501
        """SubscriptionSite - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._subscription_key = None
        self._site_key = None
        self._subscription = None
        self._site = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if subscription_key is not None:
            self.subscription_key = subscription_key
        if site_key is not None:
            self.site_key = site_key
        if subscription is not None:
            self.subscription = subscription
        if site is not None:
            self.site = site

    @property
    def key(self):
        """Gets the key of this SubscriptionSite.  # noqa: E501


        :return: The key of this SubscriptionSite.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this SubscriptionSite.


        :param key: The key of this SubscriptionSite.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def subscription_key(self):
        """Gets the subscription_key of this SubscriptionSite.  # noqa: E501


        :return: The subscription_key of this SubscriptionSite.  # noqa: E501
        :rtype: int
        """
        return self._subscription_key

    @subscription_key.setter
    def subscription_key(self, subscription_key):
        """Sets the subscription_key of this SubscriptionSite.


        :param subscription_key: The subscription_key of this SubscriptionSite.  # noqa: E501
        :type: int
        """

        self._subscription_key = subscription_key

    @property
    def site_key(self):
        """Gets the site_key of this SubscriptionSite.  # noqa: E501


        :return: The site_key of this SubscriptionSite.  # noqa: E501
        :rtype: int
        """
        return self._site_key

    @site_key.setter
    def site_key(self, site_key):
        """Sets the site_key of this SubscriptionSite.


        :param site_key: The site_key of this SubscriptionSite.  # noqa: E501
        :type: int
        """

        self._site_key = site_key

    @property
    def subscription(self):
        """Gets the subscription of this SubscriptionSite.  # noqa: E501


        :return: The subscription of this SubscriptionSite.  # noqa: E501
        :rtype: Subscription
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription):
        """Sets the subscription of this SubscriptionSite.


        :param subscription: The subscription of this SubscriptionSite.  # noqa: E501
        :type: Subscription
        """

        self._subscription = subscription

    @property
    def site(self):
        """Gets the site of this SubscriptionSite.  # noqa: E501


        :return: The site of this SubscriptionSite.  # noqa: E501
        :rtype: Site
        """
        return self._site

    @site.setter
    def site(self, site):
        """Sets the site of this SubscriptionSite.


        :param site: The site of this SubscriptionSite.  # noqa: E501
        :type: Site
        """

        self._site = site

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubscriptionSite, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionSite):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
