# coding: utf-8

"""
    Recruit Database

    Groups of services that manage the data for the 247Sports recruiting database.<br>                                         Documentation for this silo can be found here:                                         <a target=\"_blank\" href=\"https://atlassian.cbsi.com/confluence/display/TWOSPORTS/RDB+Information\">                                         Recruit Database Documentation</a>  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'int',
        'user_key': 'int',
        'account_user_key': 'int',
        'last_login': 'datetime',
        'user': 'User',
        'account_user': 'User'
    }

    attribute_map = {
        'key': 'key',
        'user_key': 'userKey',
        'account_user_key': 'accountUserKey',
        'last_login': 'lastLogin',
        'user': 'user',
        'account_user': 'accountUser'
    }

    def __init__(self, key=None, user_key=None, account_user_key=None, last_login=None, user=None, account_user=None):  # noqa: E501
        """UserAccount - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._user_key = None
        self._account_user_key = None
        self._last_login = None
        self._user = None
        self._account_user = None
        self.discriminator = None
        if key is not None:
            self.key = key
        self.user_key = user_key
        self.account_user_key = account_user_key
        if last_login is not None:
            self.last_login = last_login
        if user is not None:
            self.user = user
        if account_user is not None:
            self.account_user = account_user

    @property
    def key(self):
        """Gets the key of this UserAccount.  # noqa: E501


        :return: The key of this UserAccount.  # noqa: E501
        :rtype: int
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this UserAccount.


        :param key: The key of this UserAccount.  # noqa: E501
        :type: int
        """

        self._key = key

    @property
    def user_key(self):
        """Gets the user_key of this UserAccount.  # noqa: E501


        :return: The user_key of this UserAccount.  # noqa: E501
        :rtype: int
        """
        return self._user_key

    @user_key.setter
    def user_key(self, user_key):
        """Sets the user_key of this UserAccount.


        :param user_key: The user_key of this UserAccount.  # noqa: E501
        :type: int
        """
        if user_key is None:
            raise ValueError("Invalid value for `user_key`, must not be `None`")  # noqa: E501

        self._user_key = user_key

    @property
    def account_user_key(self):
        """Gets the account_user_key of this UserAccount.  # noqa: E501


        :return: The account_user_key of this UserAccount.  # noqa: E501
        :rtype: int
        """
        return self._account_user_key

    @account_user_key.setter
    def account_user_key(self, account_user_key):
        """Sets the account_user_key of this UserAccount.


        :param account_user_key: The account_user_key of this UserAccount.  # noqa: E501
        :type: int
        """
        if account_user_key is None:
            raise ValueError("Invalid value for `account_user_key`, must not be `None`")  # noqa: E501

        self._account_user_key = account_user_key

    @property
    def last_login(self):
        """Gets the last_login of this UserAccount.  # noqa: E501


        :return: The last_login of this UserAccount.  # noqa: E501
        :rtype: datetime
        """
        return self._last_login

    @last_login.setter
    def last_login(self, last_login):
        """Sets the last_login of this UserAccount.


        :param last_login: The last_login of this UserAccount.  # noqa: E501
        :type: datetime
        """

        self._last_login = last_login

    @property
    def user(self):
        """Gets the user of this UserAccount.  # noqa: E501


        :return: The user of this UserAccount.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this UserAccount.


        :param user: The user of this UserAccount.  # noqa: E501
        :type: User
        """

        self._user = user

    @property
    def account_user(self):
        """Gets the account_user of this UserAccount.  # noqa: E501


        :return: The account_user of this UserAccount.  # noqa: E501
        :rtype: User
        """
        return self._account_user

    @account_user.setter
    def account_user(self, account_user):
        """Sets the account_user of this UserAccount.


        :param account_user: The account_user of this UserAccount.  # noqa: E501
        :type: User
        """

        self._account_user = account_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
